export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";


export const MY_ORDER_REQUEST = "MY_ORDER_REQUEST";
export const MY_ORDER_SUCCESS = "MY_ORDER_SUCCESS";
export const MY_ORDER_FAILURE = "MY_ORDER_FAILURE";

export const ADMIN_ORDER_REQUEST = "ADMIN_ORDER_REQUEST";
export const ADMIN_ORDER_SUCCESS = "ADMIN_ORDER_SUCCESS";
export const ADMIN_ORDER_FAILURE = "ADMIN_ORDER_FAILURE";

export const ADMIN_ORDER_DELETE_REQUEST = "ADMIN_ORDER_DELETE_REQUEST";
export const ADMIN_ORDER_DELETE_SUCCESS = "ADMIN_ORDER_DELETE_SUCCESS";
export const ADMIN_ORDER_DELETE_FAILURE = "ADMIN_ORDER_DELETE_FAILURE";
export const ADMIN_ORDER_DELETE_RESET = "ADMIN_ORDER_DELETE_RESET";

export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAILURE = "UPDATE_ORDER_FAILURE";
export const UPDATE_ORDER_RESET = "UPDATE_ORDER_RESET";

export const ID_ORDER_REQUEST = "ID_ORDER_REQUEST";
export const ID_ORDER_SUCCESS = "ID_ORDER_SUCCESS";
export const ID_ORDER_FAILURE = "ID_ORDER_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";



